import { MigrationInterface, QueryRunner } from "typeorm";

export class InsertLoja1744653493463 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
        INSERT INTO loja (descricao) VALUES 
            ('Loja Principal'),
            ('Loja Mega'),
            ('Loja Premium'),
            ('Loja Digital'),
            ('Loja Express'),
            ('Loja Smart'),
            ('Loja Tech'),
            ('Loja Moderna'),
            ('Loja Futuro'),
            ('Loja Virtual'),
            ('Loja Online'),
            ('Loja Mobile'),
            ('Loja Plus'),
            ('Loja Max'),
            ('Loja Super'),
            ('Loja Ultra'),
            ('Loja Master'),
            ('Loja Executiva'),
            ('Loja Corporativa'),
            ('Loja Business'),
            ('Loja Vip'),
            ('Loja Elite'),
            ('Loja Select'),
            ('Loja Prime'),
            ('Loja Gold'),
            ('Loja Platinum'),
            ('Loja Diamond'),
            ('Loja Infinity'),
            ('Loja Alpha'),
            ('Loja Beta'),
            ('Loja Gamma'),
            ('Loja Delta'),
            ('Loja Omega'),
            ('Loja Zero'),
            ('Loja One'),
            ('Loja Two'),
            ('Loja Three'),
            ('Loja Four'),
            ('Loja Five'),
            ('Loja Six'),
            ('Loja Seven'),
            ('Loja Eight'),
            ('Loja Nine'),
            ('Loja Ten'),
            ('Loja Central Park'),
            ('Loja Times Square'),
            ('Loja Wall Street'),
            ('Loja Broadway'),
            ('Loja Fifth Avenue'),
            ('Loja Manhattan'),
            ('Loja Brooklyn'),
            ('Loja Queens'),
            ('Loja Bronx'),
            ('Loja Staten Island'),
            ('Loja Paris'),
            ('Loja London'),
            ('Loja Tokyo'),
            ('Loja Sydney'),
            ('Loja Toronto'),
            ('Loja Berlin'),
            ('Loja Madrid'),
            ('Loja Roma'),
            ('Loja Milan'),
            ('Loja Venice'),
            ('Loja Barcelona'),
            ('Loja Amsterdam'),
            ('Loja Vienna'),
            ('Loja Prague'),
            ('Loja Moscow'),
            ('Loja Beijing'),
            ('Loja Shanghai'),
            ('Loja Hong Kong'),
            ('Loja Singapore'),
            ('Loja Dubai'),
            ('Loja Istanbul'),
            ('Loja Cairo'),
            ('Loja Mumbai'),
            ('Loja Delhi'),
            ('Loja Bangkok'),
            ('Loja Seoul'),
            ('Loja Kuala Lumpur'),
            ('Loja Jakarta'),
            ('Loja Manila'),
            ('Loja Ho Chi Minh'),
            ('Loja Hanoi'),
            ('Loja Phnom Penh'),
            ('Loja Vientiane'),
            ('Loja Yangon'),
            ('Loja Kathmandu'),
            ('Loja Colombo'),
            ('Loja Dhaka'),
            ('Loja Karachi'),
            ('Loja Lahore'),
            ('Loja Tehran'),
            ('Loja Baghdad'),
            ('Loja Riyadh'),
            ('Loja Jeddah'),
            ('Loja Doha'),
            ('Loja Abu Dhabi'),
            ('Loja Muscat');
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DELETE FROM loja;`);
    }

}
